### ISSUE TITLE
Support for react 16.x?

### ISSUE THREAD

**Issue by sebakerckhof** [appmotion/apollo-augmented-hooks#8]
Hi,

I notice that the peer dependency for react requires at least v17. Since v17 doesn't contain any new features, I wonder if this is really required and if not if this could be lowered to also include react v16?

Thanks

**Comment by mindnektar** [comment]
Hi! You make a good point, there's no reason to enforce react 17 and up. I've just released v1.11.5 which requires the same peer dependencies for react and graphql as @apollo/client does, since apollo-augmented-hooks is only a wrapper for the latter. This means the requirement for react was just lowered from 17 to 16.8 - I hope that works for you!
